spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lasanhaspec
    username: guilherme
    password: 123456

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


