-- =========================================================
-- LasanhaSpec - V1__initial_schema.sql
-- =========================================================

-- 1. Tabelas Principais & Sequências

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    role VARCHAR(255),
    description VARCHAR(500),
    full_name VARCHAR(255),
    profile_images3key VARCHAR(255),
    profile_image_url VARCHAR(255),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE vehicle_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aspiration_type VARCHAR(255),
    brand VARCHAR(255),
    engine_code VARCHAR(255),
    factory_horsepower INTEGER,
    factory_torque INTEGER,
    model VARCHAR(255),
    year INTEGER,
    factory_weight INTEGER,
    acceleration0to100 DOUBLE PRECISION,
    cylinder_count INTEGER,
    displacement DOUBLE PRECISION,
    drive_type VARCHAR(255),
    fuel_type VARCHAR(255),
    gear_count INTEGER,
    top_speed DOUBLE PRECISION,
    transmission_model VARCHAR(255),
    transmission_type VARCHAR(255),
    fipe_brand_code VARCHAR(255),
    fipe_model_code VARCHAR(255),
    fipe_year_code VARCHAR(255),
    CONSTRAINT vehicle_models_drive_type_check CHECK (drive_type IN ('AWD', 'FWD', 'RWD')),
    CONSTRAINT vehicle_models_fuel_type_check CHECK (fuel_type IN ('GASOLINE', 'ETHANOL', 'FLEX', 'DIESEL', 'HYBRID', 'ELECTRIC')),
    CONSTRAINT vehicle_models_transmission_model_check CHECK (transmission_model IN ('AL4', 'AISIN_AT6', 'ZF_8HP', 'DUALOGIC', 'I_MOTION', 'EASYTRONIC', 'DSG', 'POWERSHIFT', 'CVT_JATCO', 'CVT_HONDA', 'MANUAL_5', 'MANUAL_6', 'MANUAL_4')),
    CONSTRAINT vehicle_models_transmission_type_check CHECK (transmission_type IN ('MANUAL', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'DUAL_CLUTCH', 'CVT'))
);

CREATE TABLE user_vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    nickname VARCHAR(255),
    user_id BIGINT,
    vehicle_catalog_model_id BIGINT NOT NULL,
    current_horse_power INTEGER,
    current_torque INTEGER,
    current_weight INTEGER,
    CONSTRAINT fk_user_vehicles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_vehicles_model FOREIGN KEY (vehicle_catalog_model_id) REFERENCES vehicle_models(id)
);

CREATE TABLE vehicle_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255),
    primary_image BOOLEAN,
    user_vehicle_id BIGINT NOT NULL,
    s3key VARCHAR(255),
    CONSTRAINT fk_vehicle_images_user_vehicle FOREIGN KEY (user_vehicle_id) REFERENCES user_vehicles(id)
);

CREATE TABLE chronic_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    affected_engines VARCHAR(255),
    affected_years VARCHAR(255),
    cost_max INTEGER,
    cost_min INTEGER,
    created_at TIMESTAMP,
    created_by_user_id BIGINT,
    description VARCHAR(2000) NOT NULL,
    issue_category VARCHAR(255),
    millage_max INTEGER,
    millage_min INTEGER,
    not_useful_votes INTEGER NOT NULL DEFAULT 0,
    occurrences INTEGER NOT NULL DEFAULT 0,
    repair_complexity VARCHAR(255),
    severity VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    useful_votes INTEGER NOT NULL DEFAULT 0,
    vehicle_catalog_model_id BIGINT NOT NULL,
    CONSTRAINT fk_chronic_issues_model FOREIGN KEY (vehicle_catalog_model_id) REFERENCES vehicle_models(id),
    CONSTRAINT chronic_issues_issue_category_check CHECK (issue_category IN ('MOTOR', 'SUSPENSION', 'COOLING', 'TRANSMISSION', 'ELECTRICAL', 'BODYWORK', 'BRAKES', 'TURBO', 'FUEL_SYSTEM')),
    CONSTRAINT chronic_issues_repair_complexity_check CHECK (repair_complexity IN ('DIY', 'INTERMEDIATE', 'PROFESSIONAL')),
    CONSTRAINT chronic_issues_severity_check CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chronic_issues_status_check CHECK (status IN ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED'))
);

CREATE TABLE chronic_issues_symptoms (
    chronic_issues_id BIGINT NOT NULL,
    symptoms VARCHAR(255),
    CONSTRAINT fk_chronic_issues_symptoms FOREIGN KEY (chronic_issues_id) REFERENCES chronic_issues(id)
);

CREATE TABLE chronic_issue_preventive_maintenance (
    chronic_issues_id BIGINT NOT NULL,
    preventive_maintenance VARCHAR(255),
    CONSTRAINT fk_chronic_issue_prev_maint FOREIGN KEY (chronic_issues_id) REFERENCES chronic_issues(id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP,
    user_id BIGINT NOT NULL,
    issue_id BIGINT NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id) REFERENCES chronic_issues(id)
);

CREATE TABLE issue_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    description VARCHAR(255),
    millage_at_occurrence DOUBLE PRECISION NOT NULL,
    repair_cost DOUBLE PRECISION,
    updated_at TIMESTAMP,
    issue_id BIGINT NOT NULL,
    user_vehicle_id BIGINT NOT NULL,
    CONSTRAINT uk_issue_occurrence_vehicle UNIQUE (issue_id, user_vehicle_id),
    CONSTRAINT fk_issue_occurrences_issue FOREIGN KEY (issue_id) REFERENCES chronic_issues(id),
    CONSTRAINT fk_issue_occurrences_user_vehicle FOREIGN KEY (user_vehicle_id) REFERENCES user_vehicles(id)
);

CREATE TABLE issue_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vote_type VARCHAR(255) NOT NULL,
    issue_id BIGINT NOT NULL,
    CONSTRAINT uk_issue_vote_user UNIQUE (issue_id, user_id),
    CONSTRAINT fk_issue_votes_issue FOREIGN KEY (issue_id) REFERENCES chronic_issues(id),
    CONSTRAINT fk_issue_votes_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT issue_votes_vote_type_check CHECK (vote_type IN ('USEFUL', 'NOT_USEFUL'))
);

CREATE TABLE setups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_setup BOOLEAN,
    created_at DATE,
    created_by VARCHAR(255),
    engine_stage SMALLINT,
    forged_internals BOOLEAN,
    reliability SMALLINT,
    target_aspiration_type VARCHAR(255),
    target_horse_power INTEGER,
    target_torque INTEGER,
    usage SMALLINT,
    vehicle_catalog_model_id BIGINT NOT NULL,
    CONSTRAINT fk_setups_model FOREIGN KEY (vehicle_catalog_model_id) REFERENCES vehicle_models(id),
    CONSTRAINT setups_engine_stage_check CHECK (engine_stage >= 0 AND engine_stage <= 2),
    CONSTRAINT setups_reliability_check CHECK (reliability >= 0 AND reliability <= 2),
    CONSTRAINT setups_target_aspiration_type_check CHECK (target_aspiration_type IN ('NATURALLY_ASPIRATED', 'NATURALLY_ASPPIRATED', 'TURBOCHARGED', 'SUPERCHARGED')),
    CONSTRAINT setups_usage_check CHECK (usage >= 0 AND usage <= 4)
);

CREATE TABLE current_setups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    created_at DATE,
    engine_stage VARCHAR(255),
    forged_internals BOOLEAN,
    reliability VARCHAR(255),
    target_horse_power INTEGER,
    target_torque INTEGER,
    usage_type VARCHAR(255),
    version INTEGER,
    based_on_id BIGINT,
    user_vehicle_id BIGINT NOT NULL,
    CONSTRAINT fk_current_setups_based_on FOREIGN KEY (based_on_id) REFERENCES setups(id),
    CONSTRAINT fk_current_setups_user_vehicle FOREIGN KEY (user_vehicle_id) REFERENCES user_vehicles(id),
    CONSTRAINT current_setups_engine_stage_check CHECK (engine_stage IN ('STOCK', 'STAGE_1', 'STAGE_2')),
    CONSTRAINT current_setups_reliability_check CHECK (reliability IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT current_setups_usage_type_check CHECK (usage_type IN ('DAILY', 'TRACK_DAY', 'DRAG', 'DRIFT', 'MIX'))
);